### ISSUE TITLE
operators/maintenance: Instructions for wiping state are out of date vs master

### ISSUE THREAD

**Issue by Yawning** [oasislabs/docs#154]
The following PRs to oasis-core altered the state locations that need to be removed:
 * https://github.com/oasislabs/oasis-core/pull/2472
 * https://github.com/oasislabs/oasis-core/pull/2463

The following PR added a handy command to reset the non-key material node state to that of a freshly provisioned node (to save having to manually remove files/directories):
 * https://github.com/oasislabs/oasis-core/pull/2490

Update the instructions to use `oasis-node unsafe-reset`.

**Comment by ptrus** [comment]
we can update https://docs.oasis.dev/operators/maintenance/wiping-node-state.html#state-wipe-and-keep-node-identity now to use: `oasis-node unsafe-reset`
