### ISSUE TITLE
quickstart guide: add instructions for installing openssl headers

### ISSUE THREAD

**Issue by peterjgilbert** [oasislabs/docs#17]
For both linux and mac

**Comment by peterjgilbert** [comment]
For mac, this should probably be something like: "install Homebrew via https://brew.sh/, then `brew install openssl`"

**Comment by nhynes** [comment]
Do we need this now? If we can wait a day or so, this won't be necessary any more.

**Comment by peterjgilbert** [comment]
> Do we need this now? If we can wait a day or so, this won't be necessary any more.

Ok, let's wait.
