### ISSUE TITLE
operators: Update docs for base64-encoded IDs/public keys

### ISSUE THREAD

**Issue by tjanez** [oasislabs/docs#197]
After https://github.com/oasislabs/oasis-core/pull/2640 is merged and released, the Operator docs should remove all references to hex-encoded IDs/public keys.

We can also remove the little scripts for converting between the two.

**Comment by peterjgilbert** [comment]
From a cursory review, I think only https://github.com/oasislabs/docs/blob/master/src/operators/joining-the-testnet.md and https://github.com/oasislabs/docs/blob/master/src/operators/stake-management.md need to be updated.

**Comment by tjanez** [comment]
> From a cursory review, I think only https://github.com/oasislabs/docs/blob/master/src/operators/joining-the-testnet.md and https://github.com/oasislabs/docs/blob/master/src/operators/stake-management.md need to be updated.

Yes, agreed.
