### ISSUE TITLE
Add Ankr to the Tools List

### ISSUE THREAD

**Issue by badmanj** [oasislabs/docs#250]
Add my tool to the Community-Made Resources page...

Our site app.ankr.com allows anyone to set up their Oasis node with just a few mouse-clicks. All maintenance and upgrades are managed for them, and they have full control from our easy to use interface.

It’s by far the easiest (and one of the cheapest) way for the non-technical user to “own” an Oasis node!

Please add this offering to the Tools page so that the Oasis community are aware of this option open to them. We can then tweet about this to our community, letting them know more about Oasis and if you then retweet we will between us reach many thousands of potential users across both projects.

Anne is very much aware of Ankr - we have demonstrated it to us, and we have nodes running well in the current stake-off with great uptime and performance.

My contact email is jamie@ankr.com if you need to reach out to confirm any information or to discuss further.

**Comment by Afauvre** [comment]
Thanks @badmanj. Is there a specific link we can add here that links directly to the one-touch Oasis deployment (vs. the ankr page overall)?

**Comment by badmanj** [comment]
Hi Anne. Yes the direct URL should be:

https://app.ankr.com/apps/deploy?name=oasis-validator&repository=stable&type=chart&version=20.6&appversion=20.6

Cheers - Jamie

**Comment by Afauvre** [comment]
Great. Just updated the docs. Will let you know once it's live.
