### ISSUE TITLE
I think https://help.oasislabs.com/en/ should be merged with documentation

### ISSUE THREAD

**Issue by omitar** [oasislabs/docs#39]
You can lend up on both of those. I think this is a bit confusing. I think they all should be merged into one. Or at least better integrated (shared toolbar where you can switch between one and the other). Also there seems to be duplicated content. I think it would be better if answers on help just link to documentation, when necessary.

**Comment by nhynes** [comment]
The help center is for dashboard contextual help. I also think that it’s not useful for docs, but @naheed wants to experiment. This is a data point in favor of deprecating the help center for docs.
